// <auto-generated />
using System;
using CobrancaWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CobrancaWeb.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Acionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Acionamentos");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ContratoId", "RealizadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Acionamentos_Contrato_Data");

                    b.ToTable("Acionamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acionamentos_Tipo", "[Tipo] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("DevedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TaxaJurosMensal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasDefaultValue(0.01m);

                    b.Property<decimal>("ValorOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK_Contratos");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("UQ_Contratos_Numero");

                    b.HasIndex("DevedorId", "Status")
                        .HasDatabaseName("IX_Contratos_Devedor_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DevedorId", "Status"), new[] { "Vencimento", "ValorOriginal" });

                    b.HasIndex("Status", "Vencimento")
                        .HasDatabaseName("IX_Contratos_Status_Vencimento");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "Vencimento"), new[] { "ValorOriginal" });

                    b.ToTable("Contratos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contratos_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Contratos_Taxa", "[TaxaJurosMensal] >= 0 AND [TaxaJurosMensal] <= 1");

                            t.HasCheckConstraint("CK_Contratos_Valor", "[ValorOriginal] > 0");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Devedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Devedores");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("UQ_Devedores_Documento");

                    b.ToTable("Devedores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devedores_Documento", "LEN([Documento]) IN (11, 14) AND [Documento] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.FaixaJuros", b =>
                {
                    b.Property<int>("DiasMinimos")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaMensal")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("DiasMinimos")
                        .HasName("PK_FaixasJuros");

                    b.ToTable("FaixasJuros", null, t =>
                        {
                            t.HasCheckConstraint("CK_FaixasJuros_Dias", "[DiasMinimos] >= 0");

                            t.HasCheckConstraint("CK_FaixasJuros_Taxa", "[TaxaMensal] >= 0 AND [TaxaMensal] <= 1");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Negociacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAcordo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DescontoPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAcordado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK_Negociacoes");

                    b.HasIndex("ContratoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Negociacoes_Contrato_Ativa")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("ContratoId", "Status")
                        .HasDatabaseName("IX_Negociacoes_Contrato_Status");

                    b.ToTable("Negociacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Negociacoes_Desconto", "[DescontoPercentual] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Negociacoes_Parcelas", "[QuantidadeParcelas] BETWEEN 1 AND 36");

                            t.HasCheckConstraint("CK_Negociacoes_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Negociacoes_Valor", "[ValorAcordado] > 0");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.ParcelaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NegociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK_ParcelasPagamento");

                    b.HasIndex("NegociacaoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UQ_Parcelas_NegociacaoNumero");

                    b.HasIndex("Vencimento", "PagoEm")
                        .HasDatabaseName("IX_Parcelas_Vencimento");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Vencimento", "PagoEm"), new[] { "Valor" });

                    b.ToTable("ParcelasPagamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parcelas_Numero", "[Numero] > 0");

                            t.HasCheckConstraint("CK_Parcelas_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Email");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Perfil", "[Perfil] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Acionamento", b =>
                {
                    b.HasOne("CobrancaWeb.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Acionamentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Acionamentos_Contratos");

                    b.HasOne("CobrancaWeb.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Acionamentos_Usuarios");

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("CobrancaWeb.Domain.Entities.Devedor", "Devedor")
                        .WithMany("Contratos")
                        .HasForeignKey("DevedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Contratos_Devedores");

                    b.Navigation("Devedor");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Negociacao", b =>
                {
                    b.HasOne("CobrancaWeb.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Negociacoes")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Negociacoes_Contratos");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.ParcelaPagamento", b =>
                {
                    b.HasOne("CobrancaWeb.Domain.Entities.Negociacao", "Negociacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("NegociacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Parcelas_Negociacoes");

                    b.Navigation("Negociacao");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Acionamentos");

                    b.Navigation("Negociacoes");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Devedor", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("CobrancaWeb.Domain.Entities.Negociacao", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
